### ISSUE TITLE
Update Roadmap/backlog refinement for NDC deadline

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/SSW.Rewards#209]

**Comment by matt-goldman** [comment]
- [ ] Figure out how we are going to do badges
- [ ] Figure out how we are doing currency/balance
- [ ] Setting goals (show progress to next most expensive prize)
- [ ] View prizes and their costs
- [ ] UI rebuild
- [ ] Push notifications
