### ISSUE TITLE
Social Media integration

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/SSW.Rewards#366]
@william-liebenberg @wicksipedia @matt-goldman @lukecookssw @adamcogan 

As per our conversation, Social Media integration will come in 3 phases:

## Phase 1 (MVP)
- [ ] Add **GitHub username** and **LinkedIn username/email** to user's profile page

## Phase 2
- [ ] OAuth integration with GitHub
- [ ] OAuth integration with LinkedIn
- [ ] OAuth integration with Twitter

## Phase 3
- [ ] [Automate social achievements](https://github.com/SSWConsulting/SSW.Rewards/issues/316)

**Comment by tkapa** [comment]
Low effort, High Value. Reducing friction to sign up is a big +

**Comment by tomek-i** [comment]
Considering that most devs, especially at those events like NDC will have a github & probably a gmail account, its a no brainer to have these auth providers :-D

**Comment by YazhiChen** [comment]
A great feature, but Google and GitHub logins will likely be used the most.

**Comment by KahaMason** [comment]
Great for a quick win, I think the more popular ones will be Google, GitHub & LinkedIn for logins.

**Comment by SamBWagner** [comment]
100% great idea. GO GO GO

**Comment by MattParkerDev** [comment]
Social logins will reduce barrier to entry for the app

**Comment by stephanfakossw** [comment]
Great idea

**Comment by PennyWalker** [comment]
I think this is a no-brainer - I much prefer to sign into platforms with existing IDs.

**Comment by Marxoz** [comment]
Do it! One of the biggest headaches we face at conferences is not to get people to download the app, but to get them to log in. It is a timely process, so adding this will be gold!

**Comment by hveraus** [comment]
Any social media platform we can use in China?
Please add WeChat or Weibo.

**Comment by KristenHu** [comment]
Great feature! It should be added earlier.

**Comment by Berber-Mama** [comment]
Good idea, strongly support the idea of adding a Chinese social media platform.

**Comment by matt-goldman** [comment]
> Any social media platform we can use in China? Please add WeChat or Weibo.

We can definitely do that!

**Comment by zl24622** [comment]
Like this one - small effort with high business value. No OAuth for Microsoft account?

**Comment by ozairashfaqueSSW** [comment]
Great idea - it would be very convenient

**Comment by camillars** [comment]
essential for marketing as it reduces the barriers for new users.
